### PR TITLE
Add support for wagtail admin hosted at a different prefix 

### LINKED ISSUE #51: Support wagtail admin hosted at a different prefix
`apiBase` is currently hardcoded https://github.com/wagtail/wagtail-autocomplete/blob/master/client/src/components/AutocompleteInput/index.js#L30

It would be good to support cases where the admin is hosted at a different prefix. eg `/cms/autocomplete/`

### PR DESCRIPTION
**Pull request by rrebase**
Resolve #51 to support wagtail admin hosted at a different prefix. 

Instead of using the hardcoded value it resolves from `wagtailadmin_home`

### CODE REVIEW

**Comment by rrebase** [comment]
CI probably needs to run again. It passed, but failed to update Github status. https://www.githubstatus.com/ has reports of errors

**Comment by harrislapiroff** [comment]
Stunning work! Going to try to give this a final review next week.

**Comment by Toreno96** [comment]
@harrislapiroff Is it going to be reviewed soon? 🤔

**Comment by Andruten** [comment]
I'm also interested in this feature!

**Comment by harrislapiroff** [comment]
Thanks for the poke @Andruten—I'll add this to our queue.

**Review by chigby — APPROVED** [review]
Everything here looks good to me. I tried it out on a local wagtail install with a different admin URL and it worked perfectly, assuming I also configured the autocomplete URLs to match. Well done!

**Pull request merged**
