### PR TITLE
WIP: Don't send exclusions through JS, but exclude in view

### PR DESCRIPTION
**Pull request by joeyjurjens**
I did this, because if you have lots of instances chosen, the exclude parameters is very long which can result in this error:
`414 Request-URI Too Long`

### CODE REVIEW

**Comment by joeyjurjens** [comment]
No longer a WIP as I've added some tests to test relation fields, as there was only a test for the CharField from the test app.

**Comment by chigby** [comment]
I've taken a look through this and I definitely think problem of the URL being so full of exclusions it's too long for the server needs to be addressed. Though I'm wondering if it wouldn't be a more straightforward approach with fewer changes, and more consistent with the current behavior, to change the GET request into a POST request? This would allow us to add as many exclusions to the body as we need. Do you have thoughts on this idea?

**Comment by joeyjurjens** [comment]
Hello @chigby , thank you for your reply. 

I've thought about changing this to a POST request as well, as that was my initial idea.

However, I implemented it this way  because in my opinion this is something the backend can and should handle, but I agree that that the changes I made are quite much and I didn't expect that when I started writing it. It also might bring extra complexity.

I wouldn't mind doing it the way you suggested, if that means it'll get merged, cause then I don't need to maintain the fork.

Let me know! :)

**Comment by chigby** [comment]
@joeyjurjens Thanks for bearing with me a little, and sorry about the initial long delay from you having put in the work on this PR.

The more I think about this situation, the more I wonder how necessary it is for us to be performing "exclusions" at all. I have tried to see if I could figure out why this feature was there from the beginning, but I could not. Maybe it's to save some kilobytes in the response size? It does not seem integral to the functionality, since from what I can tell the input components on the front-end are already doing some basic filtering so that the selected values don't end up in the suggestions list ([for example](https://github.com/joeyjurjens/wagtail-autocomplete/blob/main/client/src/components/AutocompleteInput/Single.js#L38)). Yet these are precisely the values that are being excluded on the back end, thus maybe we are doing the work twice?

So thinking this does make me slightly more wary of adding complexity in this area if maybe the direction we ought to be going is removing that feature completely. Though I could be mistaken here!

And I also want to make sure we can fix the problem you are having :) I think the fastest way to that would be to use the POST method, which I would be happy to merge right away if you update this PR or open a new one. To me, and sorry to be so picky about this, the method used in this PR is enough of a change that I would at least want to consult with @harrislapiroff about whether we desire the exclude feature at all before merging it.

**Comment by joeyjurjens** [comment]
@chigby The exclusions actually do have a purpose. At first I thought it didn't as well, but the view returns a limited queryset: https://github.com/wagtail/wagtail-autocomplete/blob/main/wagtailautocomplete/views.py#L81

Where the limit is also a optional GET parameter you can send: https://github.com/wagtail/wagtail-autocomplete/blob/main/wagtailautocomplete/views.py#L62

If you don't exclude existing values first, there's a possibility the limited queryset contain existing values, which the JS will then filter out and the user sees no autocomplete dropdown. Even though there could possibly be other values that aren't yet chosen.

**Comment by chigby** [comment]
Hmm, good point about the limit. I figured I was overlooking something, thanks for the explanation. We probably do want to keep it around in this case :)

One thing I am still slightly concerned about with excluding server-side is that if your page has an existing relationship, and you are editing the page and you remove it from the autocomplete box by clicking the "X", then there is no way to retrieve that entry without reloading the page. The relationship is not removed, so no data is being lost or anything, but it is a change from how the current system works and could possibly be confusing for the user?

**Comment by joeyjurjens** [comment]
That's a good point. I guess changing the GET to a POST would be the best and most ideal approach for everything, so I'll implement it that way soon. I'll mark this PR a WIP and let you know once it's done.

**Comment by joeyjurjens** [comment]
Closing this PR as it's replaced with this one: https://github.com/wagtail/wagtail-autocomplete/pull/127

@chigby Please have a look whenever you can :)

**Pull request closed without merging**
