### PR TITLE
Wagtail 4 upgrades

### PR DESCRIPTION
**Pull request by SaptakS**
Closed https://github.com/wagtail/wagtail-autocomplete/pull/172 by mistake. Continuation of that.

### CODE REVIEW

**Comment by SaptakS** [comment]
@chigby I think the tests are now passing as they should. I think we need to update in settings somewhere in the repo that we don't need to require build workflow but instead the other python tests.

**Comment by chigby** [comment]
@SaptakS these changes are looking really good! I agree with you about the repo configuration. I don't have admin access either--maybe it's something @harrislapiroff can edit?

**Comment by harrislapiroff** [comment]
I've removed `build` from the repo branch protections. I wasn't able to add the other status checks, possibly because they're not on `main`—but also is there a way to specify these in repo config files instead of settings? Should look into that.

**Review by harrislapiroff — APPROVED** [review]
I haven't reviewed this, but since it's largely someone else's code that *you* reviewed @SaptakS, I'm rubber stamping it for you.

**Pull request merged**
