### PR TITLE
Update and refactor the panel and widget code

### PR DESCRIPTION
**Pull request by jeromelebleu**
## Breaking
* Drop deprecated `page_type` and `is_single` arguments from `AutocompletePanel`

## Improvements
* Update the panel and widget codes based on panels of `wagtail.admin.edit_handlers` - mainly `PageChooserPanel`

## Tests
* Refactor and complete tests to cover all the panel and widget codes - contributes to #27 

---

Depends on #72

### CODE REVIEW

**Comment by jeromelebleu** [comment]
@harrislapiroff If we can drop Wagtail 2.3 as you pointed out, tests would pass and we could keep `wagtail.admin.staticfiles.versioned_static`! :)

**Comment by harrislapiroff** [comment]
Wow, very intrigued to look through this! Will review most likely sometime next week.

**Comment by jeromelebleu** [comment]
I believe that you may not find some time yet to review this PR. However, here is a quick bump to prevent it gets lost - especially from my memory if it needs explanations! Thanks in advance!

**Comment by jeromelebleu** [comment]
@harrislapiroff I have other proposal of changes and features for this great application but I cannot wait as it is needed for another project. I will continue so on the [develop](https://github.com/jeromelebleu/wagtail-autocomplete/tree/develop) branch of my fork. I will try as much as possible to split changes into small PR. I let you see about the future of them and would be happy to talk about that and help, as always.

**Review by chigby — APPROVED** [review]
I've reviewed this code and reconciled it as much as possible with the main branch. I had to make a few changes to some tests that were added to main later in order to maintain compatibility with the new test model structure, but I think that it works out for the best in the end.

Overall I think these changes are good for the structure and overall setup of the code in terms of bringing it in line with the current wagtail idioms. So I'm going to merge it.

**Pull request merged**
